# Generated by Django 4.2.17 on 2026-02-02 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StorageLocation",
        ),
    ]
