# Generated by Django 4.2.17 on 2026-06-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formz", "0002_delete_storagelocation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="species",
            old_name="show_in_cell_line_collection",
            new_name="show_for_cell_line",
        ),
        migrations.AlterField(
            model_name="species",
            name="show_for_cell_line",
            field=models.BooleanField(
                default=False, verbose_name="show as organism in 'Cell lines'?"
            ),
        ),
        migrations.AddField(
            model_name="species",
            name="show_for_other_bacterium_strain",
            field=models.BooleanField(
                default=False,
                verbose_name="show as species in 'Other bacterium strains'?",
            ),
        ),
    ]
