# Generated by Django 4.2.17 on 2026-08-03 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "formz",
            "0003_rename_show_in_cell_line_collection_species_show_for_cell_line_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="species",
            name="name_for_search",
        ),
    ]
