# Generated by Django 4.2.17 on 2026-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalplasmid",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("plasmid", "Purified plasmid"),
                    ("bacteria", "Bacterial stock"),
                    ("both", "Both"),
                ],
                default="",
                max_length=20,
                verbose_name="storage type",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plasmid",
            name="storage_type",
            field=models.CharField(
                choices=[
                    ("plasmid", "Purified plasmid"),
                    ("bacteria", "Bacterial stock"),
                    ("both", "Both"),
                ],
                default="",
                max_length=20,
                verbose_name="storage type",
            ),
            preserve_default=False,
        ),
    ]
