# Generated by Django 4.2.17 on 2026-02-10 14:03

import collection.shared.models
import common.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("formz", "0002_delete_storagelocation"),
        ("collection", "0004_historicalplasmid_storage_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellLineVirusTransient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="last changed"),
                ),
                ("created_date", models.DateField(null=True, verbose_name="created")),
                (
                    "destroyed_date",
                    models.DateField(blank=True, null=True, verbose_name="destroyed"),
                ),
            ],
            options={
                "verbose_name": "transient virus",
                "verbose_name_plural": "transient viruses",
            },
        ),
        migrations.CreateModel(
            name="HistoricalCellLineVirusTransient",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last changed"
                    ),
                ),
                ("created_date", models.DateField(null=True, verbose_name="created")),
                (
                    "destroyed_date",
                    models.DateField(blank=True, null=True, verbose_name="destroyed"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical transient virus",
                "verbose_name_plural": "historical transient viruses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LocationName",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A room, a freezer in a room, etc.",
                        max_length=255,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
            ],
            options={
                "verbose_name": "location name",
                "verbose_name_plural": "location names",
            },
        ),
        migrations.CreateModel(
            name="VirusInsect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_approval_by_pi",
                    models.BooleanField(
                        default=False, verbose_name="record creation approval"
                    ),
                ),
                (
                    "last_changed_approval_by_pi",
                    models.BooleanField(
                        default=None, null=True, verbose_name="record change approval"
                    ),
                ),
                (
                    "approval_by_pi_date_time",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="last changed"),
                ),
                (
                    "history_documents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="documents",
                    ),
                ),
                (
                    "formz_risk_group",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2)], null=True, verbose_name="risk group"
                    ),
                ),
                (
                    "destroyed_date",
                    models.DateField(blank=True, null=True, verbose_name="destroyed"),
                ),
                (
                    "history_formz_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formZ projects",
                    ),
                ),
                (
                    "history_formz_gentech_methods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="genTech methods",
                    ),
                ),
                (
                    "history_sequence_features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formz elements",
                    ),
                ),
                (
                    "history_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="locations",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "resistance",
                    models.CharField(max_length=255, verbose_name="resistance"),
                ),
                (
                    "us_e",
                    models.CharField(blank=True, max_length=255, verbose_name="use"),
                ),
                (
                    "construction",
                    models.TextField(blank=True, verbose_name="construction"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "history_helper_plasmids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="plasmids",
                    ),
                ),
                (
                    "typ_e",
                    models.CharField(
                        choices=[("baculo", "Baculovirus")],
                        default="baculo",
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                (
                    "approval_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_approval_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_createdby_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formz_gentech_methods",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The genetic method(s) used to create this record",
                        related_name="%(class)s_gentech_methods",
                        to="formz.gentechmethod",
                        verbose_name="genTech methods",
                    ),
                ),
                (
                    "formz_projects",
                    models.ManyToManyField(
                        related_name="%(class)s_formz_projects",
                        to="formz.project",
                        verbose_name="projects",
                    ),
                ),
            ],
            options={
                "verbose_name": "virus - Insect",
                "verbose_name_plural": "viruses - Insect",
            },
            bases=(
                common.models.EnhancedModelCleanMixin,
                common.models.SaveWithoutHistoricalRecord,
                collection.shared.models.CommonCollectionModelPropertiesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VirusMammalian",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_approval_by_pi",
                    models.BooleanField(
                        default=False, verbose_name="record creation approval"
                    ),
                ),
                (
                    "last_changed_approval_by_pi",
                    models.BooleanField(
                        default=None, null=True, verbose_name="record change approval"
                    ),
                ),
                (
                    "approval_by_pi_date_time",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="last changed"),
                ),
                (
                    "history_documents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="documents",
                    ),
                ),
                (
                    "formz_risk_group",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2)], null=True, verbose_name="risk group"
                    ),
                ),
                (
                    "destroyed_date",
                    models.DateField(blank=True, null=True, verbose_name="destroyed"),
                ),
                (
                    "history_formz_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formZ projects",
                    ),
                ),
                (
                    "history_formz_gentech_methods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="genTech methods",
                    ),
                ),
                (
                    "history_sequence_features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formz elements",
                    ),
                ),
                (
                    "history_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="locations",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "resistance",
                    models.CharField(max_length=255, verbose_name="resistance"),
                ),
                (
                    "us_e",
                    models.CharField(blank=True, max_length=255, verbose_name="use"),
                ),
                (
                    "construction",
                    models.TextField(blank=True, verbose_name="construction"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "history_helper_plasmids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="plasmids",
                    ),
                ),
                (
                    "typ_e",
                    models.CharField(
                        choices=[
                            ("lenti", "Lentivirus"),
                            ("retro", "Retrovirus"),
                            ("adenoassociated", "Adeno-associated virus"),
                        ],
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                (
                    "approval_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_approval_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_createdby_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formz_gentech_methods",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The genetic method(s) used to create this record",
                        related_name="%(class)s_gentech_methods",
                        to="formz.gentechmethod",
                        verbose_name="genTech methods",
                    ),
                ),
                (
                    "formz_projects",
                    models.ManyToManyField(
                        related_name="%(class)s_formz_projects",
                        to="formz.project",
                        verbose_name="projects",
                    ),
                ),
            ],
            options={
                "verbose_name": "virus - Mammalian",
                "verbose_name_plural": "viruses - Mammalian",
            },
            bases=(
                common.models.EnhancedModelCleanMixin,
                common.models.SaveWithoutHistoricalRecord,
                collection.shared.models.CommonCollectionModelPropertiesMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="history_viruses_mammalian_integrated",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="viruses - mammalian (integrated)",
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="history_viruses_transient",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="viruses (transient)",
            ),
        ),
        migrations.AddField(
            model_name="ecolistrain",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalantibody",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalcellline",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalcellline",
            name="history_viruses_mammalian_integrated",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="viruses - mammalian (integrated)",
            ),
        ),
        migrations.AddField(
            model_name="historicalcellline",
            name="history_viruses_transient",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="viruses (transient)",
            ),
        ),
        migrations.AddField(
            model_name="historicalecolistrain",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalinhibitor",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicaloligo",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalplasmid",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalsacerevisiaestrain",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalscpombestrain",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalsirna",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="historicalwormstrain",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="inhibitor",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="oligo",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="plasmid",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="sacerevisiaestrain",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="scpombestrain",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="sirna",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.AddField(
            model_name="wormstrain",
            name="history_locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
                verbose_name="locations",
            ),
        ),
        migrations.CreateModel(
            name="VirusMammalianDoc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.FileField(
                        max_length=150,
                        null=True,
                        upload_to="temp/",
                        verbose_name="file name",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=75, verbose_name="description"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="comment"
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="last changed"),
                ),
                (
                    "virus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="collection.virusmammalian",
                    ),
                ),
            ],
            options={
                "verbose_name": "virus doc - Mammalian",
                "verbose_name_plural": "virus docs - Mammalian",
            },
            bases=(models.Model, common.models.RenameFileField),
        ),
        migrations.AddField(
            model_name="virusmammalian",
            name="helper_cellline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_helper_cellline",
                to="collection.cellline",
                verbose_name="helper cell line",
            ),
        ),
        migrations.AddField(
            model_name="virusmammalian",
            name="helper_plasmids",
            field=models.ManyToManyField(
                help_text="Add both helper/packaging and specific plasmids",
                related_name="%(class)s_helper_plasmids",
                to="collection.plasmid",
                verbose_name="helper plasmids",
            ),
        ),
        migrations.AddField(
            model_name="virusmammalian",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.CreateModel(
            name="VirusInsectDoc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.FileField(
                        max_length=150,
                        null=True,
                        upload_to="temp/",
                        verbose_name="file name",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=75, verbose_name="description"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="comment"
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="last changed"),
                ),
                (
                    "virus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="collection.virusinsect",
                    ),
                ),
            ],
            options={
                "verbose_name": "virus doc - Insect",
                "verbose_name_plural": "virus docs - Insect",
            },
            bases=(models.Model, common.models.RenameFileField),
        ),
        migrations.AddField(
            model_name="virusinsect",
            name="helper_cellline",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_helper_cellline",
                to="collection.cellline",
                verbose_name="helper cell line",
            ),
        ),
        migrations.AddField(
            model_name="virusinsect",
            name="helper_ecolistrain",
            field=models.ForeignKey(
                help_text="The strain used for bacmid generation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_helper_ecolistrain",
                to="collection.ecolistrain",
                verbose_name="helper E. coli",
            ),
        ),
        migrations.AddField(
            model_name="virusinsect",
            name="helper_plasmids",
            field=models.ManyToManyField(
                help_text="Add both helper/packaging and specific plasmids",
                related_name="%(class)s_helper_plasmids",
                to="collection.plasmid",
                verbose_name="helper plasmids",
            ),
        ),
        migrations.AddField(
            model_name="virusinsect",
            name="sequence_features",
            field=models.ManyToManyField(
                blank=True,
                help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                related_name="%(class)s_sequence_features",
                to="formz.sequencefeature",
                verbose_name="sequence features",
            ),
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species_risk_group",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2)],
                        null=True,
                        verbose_name="species risk group",
                    ),
                ),
                (
                    "mandatory_location",
                    models.BooleanField(
                        default=False,
                        help_text="Whether or not items in this collection must have at least one location assigned",
                        verbose_name="Mandatory location?",
                    ),
                ),
                (
                    "collection",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="storage",
                        to="contenttypes.contenttype",
                        verbose_name="collection",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="formz.species",
                        verbose_name="species",
                    ),
                ),
            ],
            options={
                "verbose_name": "storage location",
                "verbose_name_plural": "storage locations",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Primary, secondary, etc.",
                        null=True,
                        verbose_name="level",
                    ),
                ),
                (
                    "storage_temperature",
                    models.CharField(
                        choices=[
                            ("RT", "Room temperature"),
                            ("4", "4° C"),
                            ("-20", "-20° C"),
                            ("-80", "-80° C"),
                            ("-150", "-150° C"),
                        ],
                        max_length=50,
                        verbose_name="storage temperature",
                    ),
                ),
                (
                    "storage_format",
                    models.CharField(
                        choices=[
                            ("9×9", "9×9 box"),
                            ("10×10", "10×10 box"),
                            ("96", "96-well plate"),
                            ("384", "384-well plate"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="storage format",
                    ),
                ),
                (
                    "mandatory_position",
                    models.BooleanField(
                        default=False,
                        help_text='Whether or not make the "Box" and "Coordinate" fields mandatory',
                        verbose_name="Mandatory position?",
                    ),
                ),
                (
                    "coordinate_format",
                    models.CharField(
                        choices=[
                            ("alphanumeric", "Alphanumeric (e.g., A1, B3, ..., H12)"),
                            ("numeric", "Numeric (e.g., 1, 2, 3, ...)"),
                            ("none", "None"),
                        ],
                        help_text='Whether or not to force coordinates values to match the schema for the picked storage format. Does not apply to "None". e.g. A1, B3, ..., H12 for 96-well plates.',
                        max_length=50,
                        verbose_name="coordinate format",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="collection.locationname",
                        verbose_name="location",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="collection.storage",
                    ),
                ),
            ],
            options={
                "verbose_name": "location",
                "verbose_name_plural": "locations",
            },
        ),
        migrations.CreateModel(
            name="HistoricalVirusMammalian",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_approval_by_pi",
                    models.BooleanField(
                        default=False, verbose_name="record creation approval"
                    ),
                ),
                (
                    "last_changed_approval_by_pi",
                    models.BooleanField(
                        default=None, null=True, verbose_name="record change approval"
                    ),
                ),
                (
                    "approval_by_pi_date_time",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last changed"
                    ),
                ),
                (
                    "history_documents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="documents",
                    ),
                ),
                (
                    "formz_risk_group",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2)], null=True, verbose_name="risk group"
                    ),
                ),
                (
                    "destroyed_date",
                    models.DateField(blank=True, null=True, verbose_name="destroyed"),
                ),
                (
                    "history_formz_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formZ projects",
                    ),
                ),
                (
                    "history_formz_gentech_methods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="genTech methods",
                    ),
                ),
                (
                    "history_sequence_features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formz elements",
                    ),
                ),
                (
                    "history_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="locations",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "resistance",
                    models.CharField(max_length=255, verbose_name="resistance"),
                ),
                (
                    "us_e",
                    models.CharField(blank=True, max_length=255, verbose_name="use"),
                ),
                (
                    "construction",
                    models.TextField(blank=True, verbose_name="construction"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "history_helper_plasmids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="plasmids",
                    ),
                ),
                (
                    "typ_e",
                    models.CharField(
                        choices=[
                            ("lenti", "Lentivirus"),
                            ("retro", "Retrovirus"),
                            ("adenoassociated", "Adeno-associated virus"),
                        ],
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approval_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "helper_cellline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="collection.cellline",
                        verbose_name="helper cell line",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical virus - Mammalian",
                "verbose_name_plural": "historical viruses - Mammalian",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVirusInsect",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_approval_by_pi",
                    models.BooleanField(
                        default=False, verbose_name="record creation approval"
                    ),
                ),
                (
                    "last_changed_approval_by_pi",
                    models.BooleanField(
                        default=None, null=True, verbose_name="record change approval"
                    ),
                ),
                (
                    "approval_by_pi_date_time",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last changed"
                    ),
                ),
                (
                    "history_documents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="documents",
                    ),
                ),
                (
                    "formz_risk_group",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2)], null=True, verbose_name="risk group"
                    ),
                ),
                (
                    "destroyed_date",
                    models.DateField(blank=True, null=True, verbose_name="destroyed"),
                ),
                (
                    "history_formz_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formZ projects",
                    ),
                ),
                (
                    "history_formz_gentech_methods",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="genTech methods",
                    ),
                ),
                (
                    "history_sequence_features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formz elements",
                    ),
                ),
                (
                    "history_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="locations",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "resistance",
                    models.CharField(max_length=255, verbose_name="resistance"),
                ),
                (
                    "us_e",
                    models.CharField(blank=True, max_length=255, verbose_name="use"),
                ),
                (
                    "construction",
                    models.TextField(blank=True, verbose_name="construction"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "history_helper_plasmids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="plasmids",
                    ),
                ),
                (
                    "typ_e",
                    models.CharField(
                        choices=[("baculo", "Baculovirus")],
                        default="baculo",
                        max_length=15,
                        verbose_name="type",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approval_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "helper_cellline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="collection.cellline",
                        verbose_name="helper cell line",
                    ),
                ),
                (
                    "helper_ecolistrain",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The strain used for bacmid generation",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="collection.ecolistrain",
                        verbose_name="helper E. coli",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical virus - Insect",
                "verbose_name_plural": "historical viruses - Insect",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStorage",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "species_risk_group",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2)],
                        null=True,
                        verbose_name="species risk group",
                    ),
                ),
                (
                    "mandatory_location",
                    models.BooleanField(
                        default=False,
                        help_text="Whether or not items in this collection must have at least one location assigned",
                        verbose_name="Mandatory location?",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="collection",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="formz.species",
                        verbose_name="species",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical storage location",
                "verbose_name_plural": "historical storage locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLocationName",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="A room, a freezer in a room, etc.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical location name",
                "verbose_name_plural": "historical location names",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLocationItem",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "box",
                    models.CharField(blank=True, max_length=10, verbose_name="box"),
                ),
                (
                    "coordinate",
                    models.CharField(
                        blank=True,
                        help_text="For example: A1, B3, ..., P24.",
                        max_length=10,
                        verbose_name="coordinate",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="comment"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="collection.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical location item",
                "verbose_name_plural": "historical location items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLocation",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Primary, secondary, etc.",
                        null=True,
                        verbose_name="level",
                    ),
                ),
                (
                    "storage_temperature",
                    models.CharField(
                        choices=[
                            ("RT", "Room temperature"),
                            ("4", "4° C"),
                            ("-20", "-20° C"),
                            ("-80", "-80° C"),
                            ("-150", "-150° C"),
                        ],
                        max_length=50,
                        verbose_name="storage temperature",
                    ),
                ),
                (
                    "storage_format",
                    models.CharField(
                        choices=[
                            ("9×9", "9×9 box"),
                            ("10×10", "10×10 box"),
                            ("96", "96-well plate"),
                            ("384", "384-well plate"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="storage format",
                    ),
                ),
                (
                    "mandatory_position",
                    models.BooleanField(
                        default=False,
                        help_text='Whether or not make the "Box" and "Coordinate" fields mandatory',
                        verbose_name="Mandatory position?",
                    ),
                ),
                (
                    "coordinate_format",
                    models.CharField(
                        choices=[
                            ("alphanumeric", "Alphanumeric (e.g., A1, B3, ..., H12)"),
                            ("numeric", "Numeric (e.g., 1, 2, 3, ...)"),
                            ("none", "None"),
                        ],
                        help_text='Whether or not to force coordinates values to match the schema for the picked storage format. Does not apply to "None". e.g. A1, B3, ..., H12 for 96-well plates.',
                        max_length=50,
                        verbose_name="coordinate format",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="collection.locationname",
                        verbose_name="location",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="collection.storage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical location",
                "verbose_name_plural": "historical locations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCellLineVirusTransient_formz_projects",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "celllinevirustransient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="collection.celllinevirustransient",
                    ),
                ),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="collection.historicalcelllinevirustransient",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="formz.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalCellLineVirusTransient_formz_projects",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="historicalcelllinevirustransient",
            name="cell_line",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="collection.cellline",
            ),
        ),
        migrations.AddField(
            model_name="historicalcelllinevirustransient",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcelllinevirustransient",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcelllinevirustransient",
            name="virus_insect",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="collection.virusinsect",
                verbose_name="Insect virus",
            ),
        ),
        migrations.AddField(
            model_name="historicalcelllinevirustransient",
            name="virus_mammalian",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="collection.virusmammalian",
                verbose_name="Mammalian virus",
            ),
        ),
        migrations.AddField(
            model_name="celllinevirustransient",
            name="cell_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viruses_transient",
                to="collection.cellline",
            ),
        ),
        migrations.AddField(
            model_name="celllinevirustransient",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_createdby_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="celllinevirustransient",
            name="formz_projects",
            field=models.ManyToManyField(
                related_name="%(class)s_projects", to="formz.project"
            ),
        ),
        migrations.AddField(
            model_name="celllinevirustransient",
            name="virus_insect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="collection.virusinsect",
                verbose_name="Insect virus",
            ),
        ),
        migrations.AddField(
            model_name="celllinevirustransient",
            name="virus_mammalian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="collection.virusmammalian",
                verbose_name="Mammalian virus",
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="viruses_mammalian_integrated",
            field=models.ManyToManyField(
                blank=True,
                help_text="Viruses used to create this cell line",
                related_name="%(class)s_virus_mammalian_integrated",
                to="collection.virusmammalian",
                verbose_name="Integrated mammalian viruses",
            ),
        ),
        migrations.CreateModel(
            name="LocationItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "box",
                    models.CharField(blank=True, max_length=10, verbose_name="box"),
                ),
                (
                    "coordinate",
                    models.CharField(
                        blank=True,
                        help_text="For example: A1, B3, ..., P24.",
                        max_length=10,
                        verbose_name="coordinate",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="comment"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="collection.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="collection__content_f39406_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("storage", "level"),
                name="unique_location_level",
                violation_error_message="The level of a location must be unique.",
            ),
        ),
        migrations.AddConstraint(
            model_name="celllinevirustransient",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("virus_insect__isnull", True),
                        ("virus_mammalian__isnull", False),
                    ),
                    models.Q(
                        ("virus_insect__isnull", False),
                        ("virus_mammalian__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="mammalian_or_insect_virus_not_both",
            ),
        ),
    ]
