# Generated by Django 4.2.17 on 2026-03-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0005_celllinevirustransient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalplasmid",
            old_name="map",
            new_name="map_dna",
        ),
        migrations.RenameField(
            model_name="historicalwormstrainallele",
            old_name="map",
            new_name="map_dna",
        ),
        migrations.RenameField(
            model_name="plasmid",
            old_name="map",
            new_name="map_dna",
        ),
        migrations.RenameField(
            model_name="wormstrainallele",
            old_name="map",
            new_name="map_dna",
        ),
        migrations.RemoveField(
            model_name="historicalplasmid",
            name="map_gbk",
        ),
        migrations.RemoveField(
            model_name="historicalplasmid",
            name="map_png",
        ),
        migrations.RemoveField(
            model_name="historicalwormstrainallele",
            name="map_gbk",
        ),
        migrations.RemoveField(
            model_name="historicalwormstrainallele",
            name="map_png",
        ),
        migrations.RemoveField(
            model_name="plasmid",
            name="map_gbk",
        ),
        migrations.RemoveField(
            model_name="plasmid",
            name="map_png",
        ),
        migrations.RemoveField(
            model_name="wormstrainallele",
            name="map_gbk",
        ),
        migrations.RemoveField(
            model_name="wormstrainallele",
            name="map_png",
        ),
        migrations.AlterField(
            model_name="historicalplasmid",
            name="map_dna",
            field=models.TextField(
                blank=True,
                help_text="Only GenBank (.gb, .gbk) or SnapGene (.dna) files, max. 2 MB",
                max_length=100,
                verbose_name="Map",
            ),
        ),
        migrations.AlterField(
            model_name="historicalwormstrainallele",
            name="map_dna",
            field=models.TextField(
                blank=True,
                help_text="Only GenBank (.gb, .gbk) or SnapGene (.dna) files, max. 2 MB",
                max_length=100,
                verbose_name="Map",
            ),
        ),
        migrations.AlterField(
            model_name="plasmid",
            name="map_dna",
            field=models.FileField(
                blank=True,
                help_text="Only GenBank (.gb, .gbk) or SnapGene (.dna) files, max. 2 MB",
                upload_to="collection/plasmid/map_dna/",
                verbose_name="Map",
            ),
        ),
        migrations.AlterField(
            model_name="wormstrainallele",
            name="map_dna",
            field=models.FileField(
                blank=True,
                help_text="Only GenBank (.gb, .gbk) or SnapGene (.dna) files, max. 2 MB",
                upload_to="collection/wormstrainallele/map_dna/",
                verbose_name="Map",
            ),
        ),
    ]
