# Generated by Django 4.2.17 on 2026-06-23 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0006_rename_map_historicalplasmid_map_dna_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvirusinsect",
            name="type_other",
            field=models.CharField(
                blank=True,
                help_text="If virus type is not in the list above, specify it here",
                max_length=255,
                verbose_name="Other type",
            ),
        ),
        migrations.AddField(
            model_name="historicalvirusmammalian",
            name="type_other",
            field=models.CharField(
                blank=True,
                help_text="If virus type is not in the list above, specify it here",
                max_length=255,
                verbose_name="Other type",
            ),
        ),
        migrations.AddField(
            model_name="virusinsect",
            name="type_other",
            field=models.CharField(
                blank=True,
                help_text="If virus type is not in the list above, specify it here",
                max_length=255,
                verbose_name="Other type",
            ),
        ),
        migrations.AddField(
            model_name="virusmammalian",
            name="type_other",
            field=models.CharField(
                blank=True,
                help_text="If virus type is not in the list above, specify it here",
                max_length=255,
                verbose_name="Other type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalvirusinsect",
            name="typ_e",
            field=models.CharField(
                choices=[("baculo", "Baculovirus"), ("other", "Other")],
                default="baculo",
                max_length=15,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalvirusmammalian",
            name="typ_e",
            field=models.CharField(
                choices=[
                    ("lenti", "Lentivirus"),
                    ("retro", "Retrovirus"),
                    ("adenoassociated", "Adeno-associated virus"),
                    ("other", "Other"),
                ],
                max_length=15,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="virusinsect",
            name="helper_cellline",
            field=models.ForeignKey(
                blank=True,
                help_text="The cell line used to produce the virus",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_helper_cellline",
                to="collection.cellline",
                verbose_name="helper cell line",
            ),
        ),
        migrations.AlterField(
            model_name="virusinsect",
            name="helper_ecolistrain",
            field=models.ForeignKey(
                blank=True,
                help_text="The strain used for bacmid generation",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_helper_ecolistrain",
                to="collection.ecolistrain",
                verbose_name="helper E. coli",
            ),
        ),
        migrations.AlterField(
            model_name="virusinsect",
            name="helper_plasmids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Add both helper/packaging and specific plasmids",
                related_name="%(class)s_helper_plasmids",
                to="collection.plasmid",
                verbose_name="helper plasmids",
            ),
        ),
        migrations.AlterField(
            model_name="virusinsect",
            name="typ_e",
            field=models.CharField(
                choices=[("baculo", "Baculovirus"), ("other", "Other")],
                default="baculo",
                max_length=15,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="virusmammalian",
            name="helper_cellline",
            field=models.ForeignKey(
                blank=True,
                help_text="The cell line used to produce the virus",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_helper_cellline",
                to="collection.cellline",
                verbose_name="helper cell line",
            ),
        ),
        migrations.AlterField(
            model_name="virusmammalian",
            name="helper_plasmids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Add both helper/packaging and specific plasmids",
                related_name="%(class)s_helper_plasmids",
                to="collection.plasmid",
                verbose_name="helper plasmids",
            ),
        ),
        migrations.AlterField(
            model_name="virusmammalian",
            name="typ_e",
            field=models.CharField(
                choices=[
                    ("lenti", "Lentivirus"),
                    ("retro", "Retrovirus"),
                    ("adenoassociated", "Adeno-associated virus"),
                    ("other", "Other"),
                ],
                max_length=15,
                verbose_name="type",
            ),
        ),
    ]
