# Generated by Django 4.2.17 on 2026-06-24 12:33

import django.contrib.postgres.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models

import collection.shared.models
import common.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "formz",
            "0003_rename_show_in_cell_line_collection_species_show_for_cell_line_and_more",
        ),
        ("collection", "0007_historicalvirusinsect_type_other_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherBacteriumStrain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_approval_by_pi",
                    models.BooleanField(
                        default=False, verbose_name="record creation approval"
                    ),
                ),
                (
                    "last_changed_approval_by_pi",
                    models.BooleanField(
                        default=None, null=True, verbose_name="record change approval"
                    ),
                ),
                (
                    "approval_by_pi_date_time",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="last changed"),
                ),
                (
                    "history_documents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="documents",
                    ),
                ),
                (
                    "formz_risk_group",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2)], null=True, verbose_name="risk group"
                    ),
                ),
                (
                    "destroyed_date",
                    models.DateField(blank=True, null=True, verbose_name="destroyed"),
                ),
                (
                    "history_formz_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formZ projects",
                    ),
                ),
                (
                    "history_sequence_features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formz elements",
                    ),
                ),
                (
                    "history_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="locations",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("genotype", models.TextField(blank=True, verbose_name="genotype")),
                (
                    "background",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="background"
                    ),
                ),
                (
                    "resistance",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="resistance"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="supplier"
                    ),
                ),
                (
                    "us_e",
                    models.CharField(blank=True, max_length=255, verbose_name="use"),
                ),
                (
                    "note",
                    models.TextField(blank=True, max_length=255, verbose_name="note"),
                ),
                (
                    "approval_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_approval_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_createdby_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "formz_projects",
                    models.ManyToManyField(
                        related_name="%(class)s_formz_projects",
                        to="formz.project",
                        verbose_name="projects",
                    ),
                ),
                (
                    "sequence_features",
                    models.ManyToManyField(
                        blank=True,
                        help_text='Use only when a feature is not present in the chosen plasmid(s), if any. Searching against the aliases of a feature is case-sensitive. <a href="/formz/sequencefeature/" target="_blank">View all/Change</a>',
                        related_name="%(class)s_sequence_features",
                        to="formz.sequencefeature",
                        verbose_name="sequence features",
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="formz.species",
                        verbose_name="species",
                    ),
                ),
            ],
            options={
                "verbose_name": "strain - Other Bacterium",
                "verbose_name_plural": "strains - Other Bacterium",
            },
            bases=(
                collection.shared.models.CommonCollectionModelPropertiesMixin,
                common.models.SaveWithoutHistoricalRecordMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="OtherBacteriumStrainDoc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.FileField(
                        max_length=150,
                        null=True,
                        upload_to="temp/",
                        verbose_name="file name",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=75, verbose_name="description"),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="comment"
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="last changed"),
                ),
                (
                    "other_bacterium_strain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="collection.otherbacteriumstrain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Other bacterium strain document",
            },
            bases=(models.Model, common.models.RenameFileField),
        ),
        migrations.CreateModel(
            name="HistoricalOtherBacteriumStrain",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_approval_by_pi",
                    models.BooleanField(
                        default=False, verbose_name="record creation approval"
                    ),
                ),
                (
                    "last_changed_approval_by_pi",
                    models.BooleanField(
                        default=None, null=True, verbose_name="record change approval"
                    ),
                ),
                (
                    "approval_by_pi_date_time",
                    models.DateTimeField(default=None, null=True),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="last changed"
                    ),
                ),
                (
                    "history_documents",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="documents",
                    ),
                ),
                (
                    "formz_risk_group",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2)], null=True, verbose_name="risk group"
                    ),
                ),
                (
                    "destroyed_date",
                    models.DateField(blank=True, null=True, verbose_name="destroyed"),
                ),
                (
                    "history_formz_projects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formZ projects",
                    ),
                ),
                (
                    "history_sequence_features",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="formz elements",
                    ),
                ),
                (
                    "history_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="locations",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("genotype", models.TextField(blank=True, verbose_name="genotype")),
                (
                    "background",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="background"
                    ),
                ),
                (
                    "resistance",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="resistance"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="supplier"
                    ),
                ),
                (
                    "us_e",
                    models.CharField(blank=True, max_length=255, verbose_name="use"),
                ),
                (
                    "note",
                    models.TextField(blank=True, max_length=255, verbose_name="note"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approval_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "species",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="formz.species",
                        verbose_name="species",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical strain - Other Bacterium",
                "verbose_name_plural": "historical strains - Other Bacterium",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
