# Generated by Django 4.2.17 on 2025-03-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0251_alter_cellline_sequence_features_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaloligo",
            name="sequence",
            field=models.CharField(
                db_index=True, max_length=2048, verbose_name="sequence"
            ),
        ),
        migrations.AlterField(
            model_name="oligo",
            name="sequence",
            field=models.CharField(
                db_collation="case_insensitive",
                max_length=2048,
                unique=True,
                verbose_name="sequence",
            ),
        ),
    ]
