# Generated by Django 4.2.17 on 2025-05-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="is_pi",
            field=models.BooleanField(
                default=False, verbose_name="is principal investigator?"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_system_user",
            field=models.BooleanField(default=False, verbose_name="is system user?"),
        ),
        migrations.AddField(
            model_name="user",
            name="oidc_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="OIDC identifier",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="case_insensitive",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
