# Generated by Django 4.2.17 on 2025-09-03 08:47

from django.db import migrations, models


def create_layout(apps, schema_editor):
    LayoutFrontend = apps.get_model("common", "LayoutFrontend")
    LayoutFrontend.objects.create(id=1)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_user_managers_user_is_pi_user_is_system_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LayoutFrontend",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        default="light", max_length=24, verbose_name="theme"
                    ),
                ),
                (
                    "primary_colour",
                    models.CharField(
                        default="emerald", max_length=24, verbose_name="primary_colour"
                    ),
                ),
                (
                    "surface_colour",
                    models.CharField(
                        default="zinc", max_length=24, verbose_name="surface_colour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Layout - Frontend",
            },
        ),
        migrations.RunPython(create_layout),
    ]
