# Generated by Django 4.2.17 on 2025-03-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_user_is_pi_user_oidc_id"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="case_insensitive",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
