# Generated by Django 4.2.17 on 2025-03-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_alter_user_managers_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_user",
            field=models.BooleanField(default=False, verbose_name="is system user?"),
        ),
    ]
