# Generated by Django 4.2.17 on 2026-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_layoutfrontend"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LayoutFrontend",
        ),
        migrations.AddField(
            model_name="user",
            name="primary_colour",
            field=models.CharField(
                default="emerald", max_length=24, verbose_name="primary_colour"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="surface_colour",
            field=models.CharField(
                default="zinc", max_length=24, verbose_name="surface_colour"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.CharField(
                default="light", max_length=24, verbose_name="theme"
            ),
        ),
    ]
