# Generated by Django 4.2.17 on 2026-09-14 10:32

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("lab_name", models.CharField(default="Smith", max_length=50)),
                (
                    "site_title",
                    models.CharField(default="BenchBaze - Smith", max_length=255),
                ),
                (
                    "lab_abbreviation_for_files",
                    models.CharField(default="", max_length=10),
                ),
                (
                    "worm_strain_regex",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "worm_strain_lab_id_default",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "worm_allele_lab_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "worm_allele_lab_id_default",
                    models.CharField(default="", max_length=50),
                ),
                (
                    "ecoli_strain_ids_default",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "plasmid_storage_type",
                    models.CharField(
                        choices=[
                            ("plasmid", "Purified plasmid"),
                            ("bacteria", "Bacterial stock"),
                            ("both", "Both"),
                        ],
                        default="plasmid",
                        max_length=20,
                    ),
                ),
                (
                    "helper_ecoli_virus_insect_id_default",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "helper_cellline_virus_insect_id_default",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "order_email_addresses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "oidc_allowed_groups",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "oidc_allowed_user_emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=255),
                        blank=True,
                        default=list,
                        help_text="All emails should be in lowercase.",
                        size=None,
                    ),
                ),
                (
                    "ms_teams_webhook_logger",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "ms_teams_webhook_purchasing",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("snapgene_enabled", models.BooleanField(default=False)),
                ("docs_url", models.URLField(default="", max_length=500)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("trial", models.BooleanField(default=False)),
                ("trial_start_date", models.DateField(blank=True, null=True)),
                ("trial_end_date", models.DateField(blank=True, null=True)),
                ("paid_until", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
