# Generated by Django 4.2.17 on 2026-09-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="docs_url",
            field=models.URLField(default="", max_length=500),
        ),
    ]
