# Generated by Django 4.2.17 on 2025-05-15 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("created", "created"), ("changed", "changed")],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Max. 255 characters",
                        max_length=255,
                        verbose_name="message",
                    ),
                ),
                ("message_date_time", models.DateTimeField(blank=True, null=True)),
                (
                    "edited",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="edited?"
                    ),
                ),
                ("created_date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "activity_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "approval",
                "verbose_name_plural": "approvals",
            },
        ),
    ]
