# Generated by Django 4.2.17 on 2025-05-15 16:26

import common.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import purchasing.order.models
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostUnit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Description"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="Check it, if you want to HIDE this cost unit from the 'Add new order' form",
                        verbose_name="deactivate?",
                    ),
                ),
            ],
            options={
                "verbose_name": "cost unit",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GhsSymbol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="code"),
                ),
                (
                    "pictogram",
                    models.ImageField(
                        help_text="only .png images, max. 2 MB",
                        upload_to="temp/",
                        verbose_name="pictogram",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "GHS symbol",
            },
            bases=(models.Model, common.models.RenameFileField),
        ),
        migrations.CreateModel(
            name="HazardStatement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="code"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                ("is_cmr", models.BooleanField(default=False, verbose_name="is CMR?")),
            ],
            options={
                "verbose_name": "hazard statement",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="name"),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=False,
                        help_text="Check it, if you want to HIDE this location from the 'Add new order' form ",
                        verbose_name="deactivate?",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MsdsForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=255, verbose_name="label"),
                ),
                (
                    "name",
                    models.FileField(
                        help_text="max. 2 MB",
                        unique=True,
                        upload_to="purchasing/msdsform/",
                        verbose_name="file name",
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created"
                    ),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="last changed"
                    ),
                ),
            ],
            options={
                "verbose_name": "MSDS form",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="supplier",
                    ),
                ),
                (
                    "supplier_part_no",
                    models.CharField(
                        help_text="To see suggestions, type three characters or more",
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="supplier Part-No",
                    ),
                ),
                (
                    "internal_order_no",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="internal order number"
                    ),
                ),
                (
                    "part_description",
                    models.CharField(
                        help_text="To see suggestions, type three characters or more",
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="part description",
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "submitted"),
                            ("open", "open"),
                            ("arranged", "arranged"),
                            ("delivered", "delivered"),
                            ("cancelled", "cancelled"),
                            ("used up", "used up"),
                        ],
                        default="submitted",
                        max_length=255,
                        verbose_name="status",
                    ),
                ),
                (
                    "urgent",
                    models.BooleanField(
                        default=False, verbose_name="is this an urgent order?"
                    ),
                ),
                (
                    "delivery_alert",
                    models.BooleanField(
                        default=False, verbose_name="delivery notification?"
                    ),
                ),
                ("sent_email", models.BooleanField(default=False, null=True)),
                ("comment", models.TextField(blank=True, verbose_name="comments")),
                (
                    "order_manager_created_date_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="created in OrderManager"
                    ),
                ),
                (
                    "delivered_date",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="delivered"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=400, verbose_name="URL"),
                ),
                (
                    "cas_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="CAS number",
                    ),
                ),
                (
                    "ghs_pictogram_old",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="GHS pictogram",
                    ),
                ),
                (
                    "history_ghs_symbols",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="GHS symbols",
                    ),
                ),
                (
                    "history_signal_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="signal words",
                    ),
                ),
                (
                    "history_hazard_statements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="hazard statements",
                    ),
                ),
                (
                    "hazard_level_pregnancy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "none"),
                            ("yellow", "yellow"),
                            ("red", "red"),
                        ],
                        default="none",
                        max_length=255,
                        verbose_name="Hazard level for pregnancy",
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="created"
                    ),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="last changed"
                    ),
                ),
                (
                    "created_approval_by_pi",
                    models.BooleanField(default=False, null=True),
                ),
                (
                    "cost_unit",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.costunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ghs_symbols",
                    models.ManyToManyField(
                        blank=True,
                        related_name="order_ghs_symbols",
                        to="purchasing.ghssymbol",
                        verbose_name="GHS symbols",
                    ),
                ),
                (
                    "hazard_statements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="order_hazard_statement",
                        to="purchasing.hazardstatement",
                        verbose_name="hazard statements",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.location",
                    ),
                ),
                (
                    "msds_form",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.msdsform",
                        verbose_name="MSDS form",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
            },
            bases=(common.models.SaveWithoutHistoricalRecord, models.Model),
        ),
        migrations.CreateModel(
            name="SignalWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal_word",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="signal word"
                    ),
                ),
            ],
            options={
                "verbose_name": "signal word",
            },
        ),
        migrations.CreateModel(
            name="OrderExtraDoc",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.FileField(
                        max_length=150,
                        null=True,
                        upload_to="temp/",
                        verbose_name="file name",
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(auto_now=True, verbose_name="last changed"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="description"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchasing.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "order extra document",
            },
            bases=(models.Model, common.models.RenameFileField),
        ),
        migrations.AddField(
            model_name="order",
            name="signal_words",
            field=models.ManyToManyField(
                blank=True,
                related_name="order_signal_words",
                to="purchasing.signalword",
                verbose_name="signal words",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOrder",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="supplier",
                    ),
                ),
                (
                    "supplier_part_no",
                    models.CharField(
                        help_text="To see suggestions, type three characters or more",
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="supplier Part-No",
                    ),
                ),
                (
                    "internal_order_no",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="internal order number"
                    ),
                ),
                (
                    "part_description",
                    models.CharField(
                        help_text="To see suggestions, type three characters or more",
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="part description",
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="price",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "submitted"),
                            ("open", "open"),
                            ("arranged", "arranged"),
                            ("delivered", "delivered"),
                            ("cancelled", "cancelled"),
                            ("used up", "used up"),
                        ],
                        default="submitted",
                        max_length=255,
                        verbose_name="status",
                    ),
                ),
                (
                    "urgent",
                    models.BooleanField(
                        default=False, verbose_name="is this an urgent order?"
                    ),
                ),
                (
                    "delivery_alert",
                    models.BooleanField(
                        default=False, verbose_name="delivery notification?"
                    ),
                ),
                ("sent_email", models.BooleanField(default=False, null=True)),
                ("comment", models.TextField(blank=True, verbose_name="comments")),
                (
                    "order_manager_created_date_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="created in OrderManager"
                    ),
                ),
                (
                    "delivered_date",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="delivered"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=400, verbose_name="URL"),
                ),
                (
                    "cas_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="CAS number",
                    ),
                ),
                (
                    "ghs_pictogram_old",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[purchasing.order.models.validate_absence_airquotes],
                        verbose_name="GHS pictogram",
                    ),
                ),
                (
                    "history_ghs_symbols",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="GHS symbols",
                    ),
                ),
                (
                    "history_signal_words",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="signal words",
                    ),
                ),
                (
                    "history_hazard_statements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                        verbose_name="hazard statements",
                    ),
                ),
                (
                    "hazard_level_pregnancy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "none"),
                            ("yellow", "yellow"),
                            ("red", "red"),
                        ],
                        default="none",
                        max_length=255,
                        verbose_name="Hazard level for pregnancy",
                    ),
                ),
                (
                    "created_date_time",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="created"
                    ),
                ),
                (
                    "last_changed_date_time",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="last changed",
                    ),
                ),
                (
                    "created_approval_by_pi",
                    models.BooleanField(default=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "cost_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="purchasing.costunit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="purchasing.location",
                    ),
                ),
                (
                    "msds_form",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="purchasing.msdsform",
                        verbose_name="MSDS form",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical order",
                "verbose_name_plural": "historical orders",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
