# Generated by Django 1.11.2 on 2018-05-17 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost_unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchasing.CostUnit",
            ),
        ),
    ]
