# Generated by Django 1.11 on 2018-11-20 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0004_auto_20181116_1526"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msdsform",
            name="order",
        ),
        migrations.AddField(
            model_name="historicalorder",
            name="msds_form",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="purchasing.MsdsForm",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="msds_form",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchasing.MsdsForm",
            ),
            preserve_default=False,
        ),
    ]
