# Generated by Django 1.11 on 2018-11-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0010_auto_20181123_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="msds_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchasing.MsdsForm",
            ),
        ),
    ]
