# Generated by Django 1.11 on 2018-11-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0014_auto_20181125_0917"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorder",
            name="delivery_alert",
            field=models.BooleanField(verbose_name="Delivery notification?"),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_alert",
            field=models.BooleanField(verbose_name="Delivery notification?"),
        ),
    ]
