# Generated by Django 1.11 on 2018-12-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0026_auto_20181209_1531"),
    ]

    operations = [
        migrations.AddField(
            model_name="costunit",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Deactivate?"),
        ),
        migrations.AddField(
            model_name="location",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Deactivate?"),
        ),
    ]
