# Generated by Django 1.11 on 2018-12-13 12:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0028_auto_20181213_1035"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="costunit",
            options={"ordering": ["name"], "verbose_name": "cost unit"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["name"]},
        ),
    ]
