# Generated by Django 1.11 on 2019-01-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0030_costunit_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costunit",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Description"),
        ),
    ]
